2024-10-06 10:45:35,804 - INFO - D:\project\attandance_pro\attendance-record\attendance-record\attandance\tasks.py changed, reloading.
2024-10-06 10:46:05,039 - INFO - D:\project\attandance_pro\attendance-record\attendance-record\attandance\tasks.py changed, reloading.
2024-10-06 10:46:29,246 - ERROR - Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x0000025E683BD190>> raised: NameError("name 'directory_path' is not defined")
Traceback (most recent call last):
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\utils\dispatch\signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\fixups\django.py", line 100, in on_import_modules
    self.worker_fixup.validate_models()
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\fixups\django.py", line 140, in validate_models
    run_checks()
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\django\core\checks\urls.py", line 136, in check_custom_error_handlers
    handler = resolver.resolve_error_handler(status_code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\django\urls\resolvers.py", line 732, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
                       ^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shaista\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\project\attandance_pro\attendance-record\attendance-record\attandance_pro\urls.py", line 7, in <module>
    path('', include('attandance.urls')),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shaista\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\project\attandance_pro\attendance-record\attendance-record\attandance\urls.py", line 3, in <module>
    from attandance import views
  File "D:\project\attandance_pro\attendance-record\attendance-record\attandance\views.py", line 8, in <module>
    from .tasks import *
  File "D:\project\attandance_pro\attendance-record\attendance-record\attandance\tasks.py", line 17, in <module>
    @shared_task(directory_path)
                 ^^^^^^^^^^^^^^
NameError: name 'directory_path' is not defined
2024-10-06 10:46:29,258 - ERROR - Signal handler <promise@0x25e6838b9d0 --> <bound method Celery._autodiscover_tasks of <Celery attandance_pro at 0x25e683a65d0>>> raised: NameError("name 'directory_path' is not defined")
Traceback (most recent call last):
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\utils\dispatch\signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\vine\promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\vine\promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\app\base.py", line 694, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\app\base.py", line 703, in _autodiscover_tasks_from_fixups
    return self._autodiscover_tasks_from_names([
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\app\base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\loaders\base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\loaders\base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\loaders\base.py", line 246, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\attandance_pro\attendance-record\attendance-record\env\Lib\site-packages\celery\loaders\base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shaista\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\project\attandance_pro\attendance-record\attendance-record\attandance\tasks.py", line 17, in <module>
    @shared_task(directory_path)
                 ^^^^^^^^^^^^^^
NameError: name 'directory_path' is not defined
